# Saved by Rosetta

[AAA]
LANGUAGE=Nederlands
TRANSLATOR=Jeroen P. Broks
[ACTORS]
BALL=Bal
CREATE=Nieuwe acteur aanmaken
GHOST=Spook
GIRL=Meisje
ROBOT=Robot
WITCH=Heks
[ALGEMEEN]
ALLOWED=Toegestaan
BACK=Terug
CANCEL=Annuleren
CONTINUE=Verdergaan
NO=Nee
OFF=Uit
OK=Ok
ON=Aan
YES=Ja
[COLOR]
ALPHA=Alfa
BLUE=Blauw
GREEN=Groen
HUE=Hue
RED=Rood
SATURATION=Saturation
VALUE=Value
[CONFIGURATION]
COLORBLIND=Kleurenblindmodus
LANGUAGE=Taal
MUSIC=Muziek
SOUNDEFFECTS=Geluidseffecten
TUTORIALS=Tutorials
[EDIT]
ACTORS=Acteurs
METADATA=Metadata
NAMEPUZZLE=Geef de puzzle een naam:
NUMBERS=Aantallen
SAVEANDEXIT=De puzzle is gewijzigd.<cr><cr>Opslaan?
[GAME]
CONTINUE=Puzzle vervolgen
GIVEUP=Opgeven
MAIN=Terug naar het hoofd menu
MAINMENU=Terug naar hoofdmenu
NEXT=Volgende puzzle
OK=Ok
OTHERPACK=Ander pack
OTHERPUZZLE=Andere puzzle
PAUSE=Puzzle pauzeren
SAME=Nog eens
START=Puzzle starten
[INPUT]
BACKSPACE=Backspace
SPACE=Spatie
[LAYERS]
DECORATION=Decoratie
FLOOR=Vloer
OBJECTS=Objects
WALL=Muur
[MAINMENU]
ACHIEVEMENTS=Prestaties
BUGS=Rapporteer Bugs
CONFIGURATION=Configuratie
CREDITS=Credits
JUKEBOX=Jukebox
LEVELEDITOR=Puzzle Editor
PICKUSER=Andere Gebruiker
PLAYGAME=Speel het spel
QUIT=Stoppen
[META]
AUTHOR=Auteur
BACKGROUND=Achtergrond
MUSIC=Muziek
RANDOM=Random
SIGNATURE=Signatuur
TITLE=Titel
[MISSIONS]
BREAKAWAY=Wegbreken
BREAKCOLLECT=Breken om te verzamelen
BREAKFREE=Vrijbreken
BRINGHOME=Thuisbrengen
COLLECTOR=Verzamelaar
NORMAL=Normaal
[PACK]
ALREADYEXISTS=Pack %s bestaat al
NAMEPACK=Geef uw nieuwe puzzle pack een naam
NEWPACK=Maak een nieuw puzzle pack aan
SELECTPACK=Selecteer a.u.b. een puzzle pack
STANDARDPACK=Standaardpuzzles
[PLAYTAB]
BARRIER=Barri|`ere
BULLDOZER=Bulldozer
PLATE=Plaat
REQUIRED=Vereist
[PUZZLESELECT]
CONFIRMCREATE=Nieuwe puzzle op plek %d aanmaken?
CONFIRMKILL=Puzzle op plek %d wissen?
INDEXING=Bezig met indexeren
KILLPUZZLE=Puzzle wissen
MADEBY=door %s
NAMELESS=Naamloze Puzzle #%03d
NEWPUZZLE=Nieuwe puzzle cre|ueren
RENEW=Vernieuwen
[USERS]
ALREADYEXISTS=Gebruiker bestaat al
EMPTY=Leeg
ENTERNAME=Vul a.u.b. uw naam in
NOUSERCREATE=Wilt u een nieuwe gebruiker aanmaken?
NOUSERSLOT=Gebruikersslot nr. %d is leeg!
PICKSPOT=Kies a.u.b. een gebruikersslot
[^SYS^]
ACTIVE=Yes
CREATIONDATE=08 May 2026; 23:41:58
CREATIONTOOL=Rosetta
