# License:
# 
# BallPlay Fantasy
# Dutch Localisation
# 
# 
# 
# 	(c) Jeroen P. Broks, 2026
# 
# 		This program is free software: you can redistribute it and/or modify
# 		it under the terms of the GNU General Public License as published by
# 		the Free Software Foundation, either version 3 of the License, or
# 		(at your option) any later version.
# 
# 		This program is distributed in the hope that it will be useful,
# 		but WITHOUT ANY WARRANTY; without even the implied warranty of
# 		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# 		GNU General Public License for more details.
# 		You should have received a copy of the GNU General Public License
# 		along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# 	Please note that some references to data like pictures or audio, do not automatically
# 	fall under this licenses. Mostly this is noted in the respective files.
# 
# Version: 26.05.19 I
# End License
# Saved by Rosetta

[AAA]
LANGUAGE=Nederlands
TRANSLATOR=Jeroen P. Broks
[ALGEMEEN]
ALLOWED=Toegestaan
BACK=Terug
CANCEL=Annuleren
CONTINUE=Verdergaan
NO=Nee
OFF=Uit
OK=Ok
ON=Aan
YES=Ja
[COLOR]
BLUE=Blauw
GREEN=Groen
HUE=Hue
RED=Rood
SATURATION=Saturation
VALUE=Value
[CONFIGURATION]
COLORBLIND=Kleurenblindmodus
LANGUAGE=Taal
MUSIC=Muziek
SOUNDEFFECTS=Geluidseffecten
TUTORIALS=Tutorials
[EDIT]
ACTORS=Acteurs
METADATA=Metadata
NAMEPUZZLE=Geef de puzzle een naam:
[INPUT]
BACKSPACE=Backspace
SPACE=Spatie
[LAYERS]
DECORATION=Decoratie
FLOOR=Vloer
OBJECTS=Objects
WALL=Muur
[MAINMENU]
ACHIEVEMENTS=Prestaties
BUGS=Rapporteer Bugs
CONFIGURATION=Configuratie
CREDITS=Credits
JUKEBOX=Jukebox
LEVELEDITOR=Puzzle Editor
PICKUSER=Andere Gebruiker
PLAYGAME=Speel het spel
QUIT=Stoppen
[MISSIONS]
BREAKAWAY=Wegbreken
BREAKCOLLECT=Breken om te verzamelen
BREAKFREE=Vrijbreken
BRINGHOME=Thuisbrengen
COLLECTOR=Verzamelaar
NORMAL=Normaal
[PACK]
ALREADYEXISTS=Pack %s bestaat al
NAMEPACK=Geef uw nieuwe puzzle pack een naam
NEWPACK=Maak een nieuw puzzle pack aan
SELECTPACK=Selecteer a.u.b. een puzzle pack
STANDARDPACK=Standaardpuzzles
[PUZZLESELECT]
CONFIRMCREATE=Nieuwe puzzle op plek %d aanmaken?
CONFIRMKILL=Puzzle op plek %d wissen?
INDEXING=Bezig met indexeren
KILLPUZZLE=Puzzle wissen
MADEBY=door %s
NAMELESS=Naamloze Puzzle #%03d
NEWPUZZLE=Nieuwe puzzle cre|ueren
RENEW=Vernieuwen
[USERS]
ALREADYEXISTS=Gebruiker bestaat al
EMPTY=Leeg
ENTERNAME=Vul a.u.b. uw naam in
NOUSERCREATE=Wilt u een nieuwe gebruiker aanmaken?
NOUSERSLOT=Gebruikersslot nr. %d is leeg!
PICKSPOT=Kies a.u.b. een gebruikersslot
[^SYS^]
ACTIVE=Yes
CREATIONDATE=08 May 2026; 23:41:58
CREATIONTOOL=Rosetta
