# Saved by Rosetta

[AAA]
LANGUAGE=Nederlands
TRANSLATOR=Jeroen P. Broks
[ALGEMEEN]
ALLOWED=Toegestaan
BACK=Terug
CANCEL=Annuleren
CONTINUE=Verdergaan
NO=Nee
OFF=Uit
ON=Aan
YES=Ja
[CONFIGURATION]
COLORBLIND=Kleurenblindmodus
LANGUAGE=Taal
MUSIC=Muziek
SOUNDEFFECTS=Geluidseffecten
TUTORIALS=Tutorials
[^SYS^]
ACTIVE=Yes
CREATIONDATE=08 May 2026; 23:41:58
CREATIONTOOL=Rosetta
