# License:
# 
# BallPlay Fantasy
# English Localisation
# 
# 
# 
# 	(c) Jeroen P. Broks, 2026
# 
# 		This program is free software: you can redistribute it and/or modify
# 		it under the terms of the GNU General Public License as published by
# 		the Free Software Foundation, either version 3 of the License, or
# 		(at your option) any later version.
# 
# 		This program is distributed in the hope that it will be useful,
# 		but WITHOUT ANY WARRANTY; without even the implied warranty of
# 		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# 		GNU General Public License for more details.
# 		You should have received a copy of the GNU General Public License
# 		along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# 	Please note that some references to data like pictures or audio, do not automatically
# 	fall under this licenses. Mostly this is noted in the respective files.
# 
# Version: 26.05.19 I
# End License
# Saved by Rosetta

[AAA]
LANGUAGE=English
TRANSLATOR=Jeroen P. Broks
[ALGEMEEN]
ALLOWED=Allowed
BACK=Back
CANCEL=Cancel
CONTINUE=Continue
NO=No
OFF=Off
OK=Ok
ON=On
YES=Yes
[COLOR]
BLUE=Blue
GREEN=Green
HUE=Hue
RED=Red
SATURATION=Saturation
VALUE=Value
[CONFIGURATION]
COLORBLIND=Color Blind Mode
LANGUAGE=Language
MUSIC=Music
SOUNDEFFECTS=Sound Effects
TUTORIALS=Tutorials
[EDIT]
ACTORS=Actors
METADATA=Metadata
NAMEPUZZLE=Please name the puzzle:
[INPUT]
BACKSPACE=Backspace
SPACE=Space
[LAYERS]
DECORATION=Decoration
FLOOR=Floor
OBJECTS=Objects
WALL=Wall
[MAINMENU]
ACHIEVEMENTS=Achievements
BUGS=Report Bugs
CONFIGURATION=Configuration
CREDITS=Credits
JUKEBOX=Jukebox
LEVELEDITOR=Puzzle Editor
NEWGAME=Play Game
PICKUSER=Other User
PLAYGAME=Play The Game
QUIT=Quit
[MISSIONS]
BREAKAWAY=Break-Away
BREAKCOLLECT=Break to collect
BREAKFREE=Break-Free
BRINGHOME=Bring Home
COLLECTOR=Collector
NORMAL=Normal
[PACK]
ALREADYEXISTS=Paket %s existiert bereits
NAMEPACK=Please name your new puzzle pack
NEWPACK=Create new puzzle pack
SELECTPACK=Please select a puzzle pack
STANDARDPACK=Standard puzzles
[PUZZLESELECT]
CONFIRMCREATE=Create a new puzzle on spot #%d?
CONFIRMKILL=Delete puzzle on spot %d?
INDEXING=Indexing
KILLPUZZLE=Delete puzzle
MADEBY=by %s
NAMELESS=Nameless Puzzle #%03d
NEWPUZZLE=Create new puzzle
RENEW=Renew
[USERS]
ALREADYEXISTS=User already exists
EMPTY=Empty
ENTERNAME=Please enter your name
NOUSERCREATE=Do you want to create a new user?
NOUSERSLOT=User slot #%d is empty
PICKSPOT=Please pick a user slot
[^SYS^]
ACTIVE=Yes
CREATIONDATE=08 May 2026; 23:41:58
CREATIONTOOL=Rosetta
