# Saved by Rosetta

[AAA]
LANGUAGE=English
TRANSLATOR=Jeroen P. Broks
[ACTORS]
BALL=Ball
CREATE=Create New Actor
GHOST=Ghost
GIRL=Girl
ROBOT=Robot
WITCH=Witch
[ALGEMEEN]
ALLOWED=Allowed
BACK=Back
CANCEL=Cancel
CONTINUE=Continue
NO=No
OFF=Off
OK=Ok
ON=On
YES=Yes
[COLOR]
ALPHA=Alpha
BLUE=Blue
GREEN=Green
HUE=Hue
RED=Red
SATURATION=Saturation
VALUE=Value
[CONFIGURATION]
COLORBLIND=Color Blind Mode
LANGUAGE=Language
MUSIC=Music
SOUNDEFFECTS=Sound Effects
TUTORIALS=Tutorials
[EDIT]
ACTORS=Actors
METADATA=Metadata
NAMEPUZZLE=Please name the puzzle:
NUMBERS=Numbers
SAVEANDEXIT=Puzzle has been modified<cr><cr>Save?
[GAME]
CONTINUE=Continue puzzle
GIVEUP=Give up
GIVEUPCONFIRM=Do you really want to give up?
MAINMENU=Back to Main Menu
NEXT=Next puzzle
OK=Ok
OTHERPACK=Other pack
OTHERPUZZLE=Other puzzle
PAUSE=Pause puzzle
SAME=Retry puzzle
START=Start puzzle
[INPUT]
BACKSPACE=Backspace
SPACE=Space
[LAYERS]
DECORATION=Decoration
FLOOR=Floor
OBJECTS=Objects
WALL=Wall
[MAINMENU]
ACHIEVEMENTS=Achievements
BUGS=Report Bugs
CONFIGURATION=Configuration
CREDITS=Credits
JUKEBOX=Jukebox
LEVELEDITOR=Puzzle Editor
NEWGAME=Play Game
PICKUSER=Other User
PLAYGAME=Play The Game
QUIT=Quit
TUTORIALS=List of Tutorials
[META]
AUTHOR=Author
BACKGROUND=Background
MUSIC=Music
RANDOM=Random
SIGNATURE=Signature
TITLE=Title
[MISSIONS]
BREAKAWAY=Break-Away
BREAKCOLLECT=Break to collect
BREAKFREE=Break-Free
BRINGHOME=Bring Home
COLLECTOR=Collector
COLORSPLIT=Color-Split
NORMAL=Normal
[PACK]
ALREADYEXISTS=Paket %s existiert bereits
NAMEPACK=Please name your new puzzle pack
NEWPACK=Create new puzzle pack
SELECTPACK=Please select a puzzle pack
STANDARDPACK=Standard puzzles
[PLAYTAB]
BARRIER=Barrier
BULLDOZER=Bulldozer
PLATE=Plate
REQUIRED=Required
[PUZZLESELECT]
CONFIRMCREATE=Create a new puzzle on spot #%d?
CONFIRMKILL=Delete puzzle on spot %d?
INDEXING=Indexing
KILLPUZZLE=Delete puzzle
MADEBY=by %s
NAMELESS=Nameless Puzzle #%03d
NEWPUZZLE=Create new puzzle
RENEW=Renew
[RECORDS]
BALLS=Most balls
TIME=Fastest time
TOOLS=Least tools
[USERS]
ALREADYEXISTS=User already exists
EMPTY=Empty
ENTERNAME=Please enter your name
NOUSERCREATE=Do you want to create a new user?
NOUSERSLOT=User slot #%d is empty
PICKSPOT=Please pick a user slot
[^SYS^]
ACTIVE=Yes
CREATIONDATE=08 May 2026; 23:41:58
CREATIONTOOL=Rosetta
