# License:
# 
# BallPlay Fantasy
# German localisation
# 
# 
# 
# 	(c) Jeroen P. Broks, 2026
# 
# 		This program is free software: you can redistribute it and/or modify
# 		it under the terms of the GNU General Public License as published by
# 		the Free Software Foundation, either version 3 of the License, or
# 		(at your option) any later version.
# 
# 		This program is distributed in the hope that it will be useful,
# 		but WITHOUT ANY WARRANTY; without even the implied warranty of
# 		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# 		GNU General Public License for more details.
# 		You should have received a copy of the GNU General Public License
# 		along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# 	Please note that some references to data like pictures or audio, do not automatically
# 	fall under this licenses. Mostly this is noted in the respective files.
# 
# Version: 26.05.13
# End License
# Saved by Rosetta

[AAA]
LANGUAGE=Deutsch
TRANSLATOR=Jeroen P. Broks
[ALGEMEEN]
ALLOWED=Erlaubt
BACK=Zur|uuck
CANCEL=Abbrechen
CONTINUE=Weiter
NO=Nein
OFF=Aus
OK=Ok
ON=An
YES=Ja
[CONFIGURATION]
COLORBLIND=Farbenblindmodus
LANGUAGE=Sprache
MUSIC=Musik
SOUNDEFFECTS=Soundeffekte
TUTORIALS=Tutorials
[INPUT]
BACKSPACE=R|uucktaste
SPACE=Leertaste
[MAINMENU]
ACHIEVEMENTS=Erfolge
BUGS=Fehler melden
CONFIGURATION=Konfiguration
CREDITS=Credits
JUKEBOX=Jukebox
LEVELEDITOR=Puzzle-Editor
NEWGAME=Spiel starten
PICKUSER=Anderer Benutzer
PLAYGAME=Spiel spielen
QUIT=Beenden
[MISSIONS]
BREAKAWAY=Ausbrechen
BREAKCOLLECT=Zerbrechen zum Sammeln
BREAKFREE=Freibrechen
BRINGHOME=Nach Hause bringen
COLLECTOR=Sammler
NORMAL=Normal
[USERS]
ALREADYEXISTS=Benutzer existiert bereits
EMPTY=Leer
ENTERNAME=Bitte geben Sie Ihren Namen ein
NOUSERCREATE=Neues Profil erstellen?
NOUSERSLOT=Slot %d ist leer
PICKSPOT=W|uahlen Sie einen Benutzerplatz
[^SYS^]
ACTIVE=Yes
CREATIONDATE=09 May 2026; 13:24:03
CREATIONTOOL=Rosetta
