# License:
# 
# BallPlay Fantasy
# German localisation
# 
# 
# 
# 	(c) Jeroen P. Broks, 2026
# 
# 		This program is free software: you can redistribute it and/or modify
# 		it under the terms of the GNU General Public License as published by
# 		the Free Software Foundation, either version 3 of the License, or
# 		(at your option) any later version.
# 
# 		This program is distributed in the hope that it will be useful,
# 		but WITHOUT ANY WARRANTY; without even the implied warranty of
# 		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# 		GNU General Public License for more details.
# 		You should have received a copy of the GNU General Public License
# 		along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# 	Please note that some references to data like pictures or audio, do not automatically
# 	fall under this licenses. Mostly this is noted in the respective files.
# 
# Version: 26.06.01
# End License
# Saved by Rosetta

[AAA]
LANGUAGE=Deutsch
TRANSLATOR=Jeroen P. Broks
[ACTORS]
BALL=Ball
CREATE=Neuen Akteur erstellen
GHOST=Geist
GIRL=M|uadchen
ROBOT=Robot
WITCH=Hexe
[ALGEMEEN]
ALLOWED=Erlaubt
BACK=Zur|uuck
CANCEL=Abbrechen
CONTINUE=Weiter
NO=Nein
OFF=Aus
OK=Ok
ON=An
YES=Ja
[COLOR]
ALPHA=Alpha
BLUE=Blau
GREEN=Gr|uun
HUE=Hue
RED=Rot
SATURATION=Saturation
VALUE=Value
[CONFIGURATION]
COLORBLIND=Farbenblindmodus
LANGUAGE=Sprache
MUSIC=Musik
SOUNDEFFECTS=Soundeffekte
TUTORIALS=Tutorials
[EDIT]
ACTORS=Actors
METADATA=Metadata
NAMEPUZZLE=Bitte geben Sie dem Puzzle einen Namen:
NUMBERS=Zahlen
SAVEANDEXIT=Das Puzzle wurde geraendert.<cr><cr>Speichern?
[GAME]
CONTINUE=Weiterspielen
GIVEUP=Aufgeben
GIVEUPCONFIRM=Willst du echt aufgeben?
MAINMENU=Zur|uuck zum Hauptmen|uu
NEXT=N|uachstes Puzzle
OK=Ok
OTHERPACK=Anderes Pack
OTHERPUZZLE=Anderes Puzzle
PAUSE=Puzzle pausieren
SAME=Puzzle wiederholen
START=Puzzle starten
[INPUT]
BACKSPACE=R|uucktaste
SPACE=Leertaste
[LAYERS]
DECORATION=Dekoration
FLOOR=Boden
OBJECTS=Objekte
WALL=Wand
[MAINMENU]
ACHIEVEMENTS=Erfolge
BUGS=Fehler melden
CONFIGURATION=Konfiguration
CREDITS=Credits
JUKEBOX=Jukebox
LEVELEDITOR=Puzzle-Editor
NEWGAME=Spiel starten
PICKUSER=Anderer Benutzer
PLAYGAME=Spiel spielen
QUIT=Beenden
TUTORIALS=Tutorialliste
[META]
AUTHOR=Autor
BACKGROUND=Hintergrund
MUSIC=Musik
RANDOM=Random
SIGNATURE=Signatur
TITLE=Titel
[MISSIONS]
BREAKAWAY=Wegbrechen
BREAKCOLLECT=Zerbrechen zum Sammeln
BREAKFREE=Freibrechen
BRINGHOME=Nach Hause bringen
COLLECTOR=Sammler
NORMAL=Normal
[PACK]
ALREADYEXISTS=Paket %s ist schon da
NAMEPACK=Geben Sie bitte Ihrem Puzzlepaket einen Namen
NEWPACK=Neues Puzzlepaket erstellen
SELECTPACK=Bitte w|uahlen Sie ein Puzzlepaket
STANDARDPACK=Standardpuzzles
[PLAYTAB]
BARRIER=Barriere
BULLDOZER=Bulldozer
PLATE=Platte
REQUIRED=Ben|uotigt
[PUZZLESELECT]
CONFIRMCREATE=Neues Puzzle auf Platz %d erstellen?
CONFIRMKILL=Puzzle auf Platz %d loeschen?
INDEXING=Indizierung l|uauft
KILLPUZZLE=Puzzle l|uoschen
MADEBY=von %s
NAMELESS=Unbenanntes Puzzle #%03d
NEWPUZZLE=Neues Puzzle erstellen
RENEW=Aktualisieren
[USERS]
ALREADYEXISTS=Benutzer existiert bereits
EMPTY=Leer
ENTERNAME=Bitte geben Sie Ihren Namen ein
NOUSERCREATE=Neues Profil erstellen?
NOUSERSLOT=Slot %d ist leer
PICKSPOT=W|uahlen Sie einen Benutzerplatz
[^SYS^]
ACTIVE=Yes
CREATIONDATE=09 May 2026; 13:24:03
CREATIONTOOL=Rosetta
