# License:
# 
# BallPlay Fantasy
# Rosetta Localisation Project File
# 
# 
# 
# 	(c) Jeroen P. Broks, 2026
# 
# 		This program is free software: you can redistribute it and/or modify
# 		it under the terms of the GNU General Public License as published by
# 		the Free Software Foundation, either version 3 of the License, or
# 		(at your option) any later version.
# 
# 		This program is distributed in the hope that it will be useful,
# 		but WITHOUT ANY WARRANTY; without even the implied warranty of
# 		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# 		GNU General Public License for more details.
# 		You should have received a copy of the GNU General Public License
# 		along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# 	Please note that some references to data like pictures or audio, do not automatically
# 	fall under this licenses. Mostly this is noted in the respective files.
# 
# Version: 26.05.29
# End License
# Rosetta project

[DIRECTORIES::LINUX]
SCENARIO=/media/$User$/Scyndi/Projects/Applications/Scyndi/BallPlay Fantasy/src/Rosetta/Scenario
STRINGS=/media/$User$/Scyndi/Projects/Applications/Scyndi/BallPlay Fantasy/src/Rosetta/Strings
[EXPORT]
METHOD=ScenLang
[STRINGS]
AUTOCAT=True
KEY_AAA_0=Language
KEY_AAA_1=Translator
KEY_ACTORS_0=Ball
KEY_ACTORS_1=Ghost
KEY_ACTORS_2=Robot
KEY_ACTORS_3=Girl
KEY_ACTORS_4=Witch
KEY_ACTORS_6=Create
KEY_ALGEMEEN_0=Allowed
KEY_ALGEMEEN_1=Back
KEY_ALGEMEEN_2=Cancel
KEY_ALGEMEEN_3=Continue
KEY_ALGEMEEN_4=On
KEY_ALGEMEEN_5=Off
KEY_ALGEMEEN_6=Ok
KEY_COLOR_1=Red
KEY_COLOR_2=Green
KEY_COLOR_3=Blue
KEY_COLOR_5=Hue
KEY_COLOR_6=Saturation
KEY_COLOR_7=Value
KEY_COLOR_9=Alpha
KEY_CONFIGURATION_0=Music
KEY_CONFIGURATION_1=SoundEffects
KEY_CONFIGURATION_2=ColorBlind
KEY_CONFIGURATION_3=Tutorials
KEY_CONFIGURATION_4=Language
KEY_EDIT_0=NamePuzzle
KEY_EDIT_1=MetaData
KEY_EDIT_2=Actors
KEY_EDIT_3=Numbers
KEY_EDIT_6=SaveAndExit
KEY_GAME_0=Start
KEY_GAME_1=OtherPuzzle
KEY_GAME_2=OtherPack
KEY_GAME_3=MainMenu
KEY_GAME_4=Pause
KEY_GAME_5=Continue
KEY_GAME_6=GiveUp
KEY_GAME_7=Next
KEY_GAME_8=Same
KEY_GAME_9=Ok
KEY_INPUT_0=Space
KEY_INPUT_1=BackSpace
KEY_LAYERS_0=Floor
KEY_LAYERS_1=Wall
KEY_LAYERS_2=Decoration
KEY_LAYERS_3=Objects
KEY_MAINMENU_0=PlayGame
KEY_MAINMENU_1=LevelEditor
KEY_MAINMENU_2=Configuration
KEY_MAINMENU_3=Credits
KEY_MAINMENU_4=Jukebox
KEY_MAINMENU_5=Bugs
KEY_MAINMENU_6=Achievements
KEY_MAINMENU_8=Quit
KEY_META_0=Title
KEY_META_1=Author
KEY_META_2=Signature
KEY_META_3=Background
KEY_META_4=Music
KEY_META_5=Random
KEY_MISSIONS_0=Normal
KEY_MISSIONS_1=BreakAway
KEY_MISSIONS_2=BreakFree
KEY_MISSIONS_3=BringHome
KEY_MISSIONS_4=Collector
KEY_MISSIONS_5=BreakCollect
KEY_PACK_0=NewPack
KEY_PACK_1=StandardPack
KEY_PACK_2=SelectPack
KEY_PACK_3=NamePack
KEY_PACK_4=AlreadyExists
KEY_PLAYTAB_0=Required
KEY_PLAYTAB_1=Plate
KEY_PLAYTAB_2=Bulldozer
KEY_PLAYTAB_3=Barrier
KEY_PUZZLECOMPLETE_0=Next
KEY_PUZZLECOMPLETE_1=Other
KEY_PUZZLECOMPLETE_2=Same
KEY_PUZZLECOMPLETE_3=Back2Main
KEY_PUZZLESELECT_0=NewPuzzle
KEY_PUZZLESELECT_1=KillPuzzle
KEY_PUZZLESELECT_2=Renew
KEY_PUZZLESELECT_3=Indexing
KEY_PUZZLESELECT_4=ConfirmCreate
KEY_PUZZLESELECT_5=ConfirmKill
KEY_PUZZLESELECT_6=MadeBy
KEY_USERS_0=PickSpot
KEY_USERS_1=EnterName
KEY_USERS_2=Empty
KEY_USERS_3=NoUserSlot
KEY_USERS_4=NoUserCreate
KEY_USERS_5=AlreadyExists
LANG1=English
LANG2=Dutch
*list:AFGEKEURD
	PuzzleComplete
*end
*list:CAT_GAME
	Start
	OtherPuzzle
	OtherPack
	MainMenu
	Pause
	Continue
	GiveUp
	Next
	Same
	Ok
*end
*list:^CATEGORIES^
	AAA
	Algemeen
	Configuration
	Input
	MainMenu
	Meta
	Missions
	Pack
	PuzzleSelect
	Edit
	Layers
	Users
	Color
	Actors
	PlayTab
	Game
*end
[SUPPORT]
LANGUAGES=English,Dutch,German
LANGUAGE_DEF=English
