# Project file for a Scyndi Project
# Last modified: 08 May 2026

[AA_META]
01_TITLE=BallPlay Fantasy
02_CREATEDBY=Jeroen P. Broks
03_COPYRIGHT=(c) Jeroen P. Broks, 2026
04_LICENSE=General Public License 3
[ASSETS_MULTIDIR::JQL]
AUTHOR=JCR6 Quick Link
NOTES=If you see this in output JCR6 files, please notify Jeroen P. Broks immediately as something may have gone wrong building
PACKAGE=Assets
USE=Y
[ASSETS_MULTIDIR::TRICKY]
AUTHOR=Jeroen P. Broks
NOTES=Creative Commons - By Attribute - Non-Commercial - Share-Alike
PACKAGE=Assets
USE=Y
[DIRECTORY]
SCI_ASSETS_MULTIDIR=Y
[DIRECTORY::LINUX]
SCI_ASSETS_SOURCE=src/Assets
*list:LIBRARIES
	../Libs/SCI
	../Libs/General
	/media/tricky/Scyndi/Projects/Applications/Slyvina/Apps/SCI/SCI_Exe/IntLibs
*end
*list:SOURCEFILES
	src/Code
*end
[PACKAGE]
STORAGE=zlib
[PROJECT]
AUTHOR=Jeroen P. Broks
COPYRIGHT=(c) Jeroen P. Broks, 2026
CREATED=08 May 2026; 12:31:01
DEBUGJQLDIR=Debug
LICENSE=General Public License 3
OUTPUTNAME=BallPlay Fantasy
TITLE=BallPlay Fantasy
[SCI::MOUSE]
HIDE=Y
[SCI::SAVE]
DIR=BallPlay Fantasy
ID=19e3b3652812220e3db82cab3d201c74-3b230e637a3c602ed71b11ecbf29fa8f
[SCI::WINDOW]
ALTHEIGHT=960
ALTWIDTH=1600
CAPTION=BallPlay Fantasy
FULL SCREEN=N
USEALT=Y
WINADEPTALT=Y
WINHEIGHT=80%
WINWIDTH=95%
[SCRIPT]
BYTECODE=Y
PACKAGE=Scripts
