# License:
# 
# BallPlay Fantasy
# Rosetta Localisation Project File
# 
# 
# 
# 	(c) Jeroen P. Broks, 2026
# 
# 		This program is free software: you can redistribute it and/or modify
# 		it under the terms of the GNU General Public License as published by
# 		the Free Software Foundation, either version 3 of the License, or
# 		(at your option) any later version.
# 
# 		This program is distributed in the hope that it will be useful,
# 		but WITHOUT ANY WARRANTY; without even the implied warranty of
# 		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# 		GNU General Public License for more details.
# 		You should have received a copy of the GNU General Public License
# 		along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# 	Please note that some references to data like pictures or audio, do not automatically
# 	fall under this licenses. Mostly this is noted in the respective files.
# 
# Version: 26.05.09 II
# End License
# Rosetta project

[DIRECTORIES::LINUX]
SCENARIO=/media/$User$/Scyndi/Projects/Applications/Scyndi/BallPlay Fantasy/src/Rosetta/Scenario
STRINGS=/media/$User$/Scyndi/Projects/Applications/Scyndi/BallPlay Fantasy/src/Rosetta/Strings
[EXPORT]
METHOD=ScenLang
[STRINGS]
AUTOCAT=True
KEY_AAA_0=Language
KEY_AAA_1=Translator
KEY_ALGEMEEN_0=Allowed
KEY_ALGEMEEN_1=Back
KEY_ALGEMEEN_2=Cancel
KEY_ALGEMEEN_3=Continue
KEY_ALGEMEEN_4=On
KEY_ALGEMEEN_5=Off
KEY_ALGEMEEN_6=Ok
KEY_CONFIGURATION_0=Music
KEY_CONFIGURATION_1=SoundEffects
KEY_CONFIGURATION_2=ColorBlind
KEY_CONFIGURATION_3=Tutorials
KEY_CONFIGURATION_4=Language
KEY_MAINMENU_0=PlayGame
KEY_MAINMENU_1=LevelEditor
KEY_MAINMENU_2=Configuration
KEY_MAINMENU_3=Credits
KEY_MAINMENU_4=Jukebox
KEY_MAINMENU_5=Bugs
KEY_MAINMENU_6=PickUser
KEY_MAINMENU_7=Quit
KEY_MISSIONS_0=Normal
KEY_MISSIONS_1=BreakAway
KEY_MISSIONS_2=BreakFree
KEY_MISSIONS_3=BringHome
KEY_MISSIONS_4=Collector
KEY_MISSIONS_5=BreakCollect
KEY_USERS_0=PickSpot
KEY_USERS_1=EnterName
LANG1=English
LANG2=German
*list:CAT_AAA
*end
*list:CAT_USERS
	PickSpot
	EnterName
*end
*list:^CATEGORIES^
	AAA
	ALGEMEEN
	CONFIGURATION
	MAINMENU
	Missions
	Users
*end
[SUPPORT]
LANGUAGES=English,Dutch,German
LANGUAGE_DEF=English
