# License:
# 
# BallPlay Fantasy
# Project File
# 
# 
# 
# 	(c) Jeroen P. Broks, 2026
# 
# 		This program is free software: you can redistribute it and/or modify
# 		it under the terms of the GNU General Public License as published by
# 		the Free Software Foundation, either version 3 of the License, or
# 		(at your option) any later version.
# 
# 		This program is distributed in the hope that it will be useful,
# 		but WITHOUT ANY WARRANTY; without even the implied warranty of
# 		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# 		GNU General Public License for more details.
# 		You should have received a copy of the GNU General Public License
# 		along with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# 	Please note that some references to data like pictures or audio, do not automatically
# 	fall under this licenses. Mostly this is noted in the respective files.
# 
# Version: 26.05.15
# End License
# BallPlay Fantasy
# Jeroen P. Broks
# 
# (c) Jeroen P. Broks, 2026

[AA_META]
01_TITLE=BallPlay Fantasy
02_CREATEDBY=Jeroen P. Broks
03_COPYRIGHT=(c) Jeroen P. Broks, 2026
04_LICENSE=General Public License 3
[APPIMAGE]
CATEGORIES=Game;
DO=Y
DT.EXEC=BallPlay_Fantasy
DT.NAME=BallPlay_Fantasy
ICON=src/Assets/Tricky/GFX/Objects/Ball.png
MAXGB=6
RAMDISKDIR=/home/tricky/SCI_RAMDISK
[ASSETS_MULTIDIR::DINAMOSTAFA]
AUTHOR=DinaMostafa
NOTES=Public Domain
PACKAGE=ASSETS
USE=Y
[ASSETS_MULTIDIR::EGORE911]
AUTHOR=egore911
NOTES=Public Domain
PACKAGE=Assets
USE=Y
[ASSETS_MULTIDIR::JQL]
AUTHOR=JCR6 Quick Link
NOTES=If you see this in output JCR6 files, please notify Jeroen P. Broks immediately as something may have gone wrong building
PACKAGE=Assets
USE=Y
[ASSETS_MULTIDIR::PIXDAUS.COM]
AUTHOR=Pixdaus.com
NOTES=Artist unknown. This picture was downloaded from Pixdaus.com and according the that site released as public domain. If this is not public domain and you recognize your picture, please notify me.
PACKAGE=Assets
USE=Y
[ASSETS_MULTIDIR::TRICKY]
AUTHOR=Jeroen P. Broks
NOTES=Creative Commons - By Attribute - Non-Commercial - Share-Alike
PACKAGE=Assets
USE=Y
[ASSETS_MULTIDIR::UNKNOWN]
AUTHOR=?
NOTES=?
PACKAGE=Assets
USE=Y
[ASSETS_MULTIDIR::WARSZAWIANKA]
AUTHOR=warszawianka
NOTES=Public Domain
PACKAGE=Assets
USE=Y
[DIRECTORY]
SCI_ASSETS_MULTIDIR=Y
[DIRECTORY::LINUX]
SCI_ASSETS_SOURCE=src/Assets
*list:LIBRARIES
	../Libs/SCI
	../Libs/General
	/media/tricky/Scyndi/Projects/Applications/Slyvina/Apps/SCI/SCI_Exe/IntLibs
*end
*list:SOURCEFILES
	src/Code/Script
*end
[LINUX_BASIC]
DO=N
[PACKAGE]
STORAGE=zlib
[PROJECT]
AUTHOR=Jeroen P. Broks
COPYRIGHT=(c) Jeroen P. Broks, 2026
CREATED=08 May 2026; 12:31:01
DEBUGJQLDIR=Debug
LICENSE=General Public License 3
OUTPUTNAME=BallPlay Fantasy
TITLE=BallPlay Fantasy
[RELEASE]
DIRECTORY_LINUX=/media/$User$/Scyndi/Releases/BallPlay Fantasy
PREFSTORAGE=zlib
WINDOWS_CONSOLE_RELEASE=Y
[RELEASE_PACKAGE_MERGEWITHMAIN]
ASSETS=Y
SCRIPTS=Y
[SCI::MOUSE]
HIDE=Y
[SCI::SAVE]
DIR=BallPlay Fantasy
ID=19e3b3652812220e3db82cab3d201c74-3b230e637a3c602ed71b11ecbf29fa8f
[SCI::WINDOW]
ALTHEIGHT=960
ALTWIDTH=1600
CAPTION=BallPlay Fantasy
FULL SCREEN=N
USEALT=Y
WINADEPTALT=Y
WINHEIGHT=80%
WINWIDTH=95%
[SCORPION]
BACKALIASDO=Y
BACKALIASENTRY=GFX/MainMenu/Background.png
BACKALIASFROMPACKAGE=*MAIN
BUTTON.BACK=#00001f
BUTTON.TEXT=#ffff00
HEAD.TEXT=#ffb400
ICON=src/Assets/Tricky/GFX/Objects/Ball.png
LISTBOX.BACK=#0b0f00
LISTBOX.TEXT=#b4ff00
TEXT.TEXT=#ffffff
*list:DESCRIPTION
	A nice puzzle game. The balls will run and all you have is a few plates and barriers with which you can try to change their direction.
	Specific tasks can be set by level, and you got to do without getting too many balls destroyed.
	Are you up to the challenge?
*end
[SCRIPT]
BYTECODE=Y
PACKAGE=Scripts
[SOLID::ASSETS]
FONTS=N
FONTS/RYANNA.JFBF=Y
GFX=Y
GFX/ALGEMEEN=N
GFX/ARROWS=Y
GFX/MAIN MENU=N
GFX/MAINMENU=N
GFX/OBJECTS=Y
GFX/PLATES=Y
LOCALISATION=N
MUSIC=N
MUSIC/SYS=N
PUZZLES/BALLPLAY FANTASY=N
[SOLID::SCRIPTS]
LIBS=N
LIBS/SCI=Y
SCRIPT/FLOW=N
SCRIPT/START=N
SCRIPT/USE/ANY.UWN=N
SCRIPT/USE/ANYWAY.SCYNDIBUNDLE=Y
SCRIPT/USE/PUZ.UWN=Y
[MERGE]
*list:MERGE
*end
