# Rosetta project

[DIRECTORIES::LINUX]
SCENARIO=/media/$User$/Scyndi/Projects/Applications/Scyndi/BallPlay Fantasy/src/Rosetta/Scenario
STRINGS=/media/$User$/Scyndi/Projects/Applications/Scyndi/BallPlay Fantasy/src/Rosetta/Strings
[EXPORT]
METHOD=ScenLang
[STRINGS]
AUTOCAT=True
KEY_AAA_0=Language
KEY_AAA_1=Translator
KEY_ALGEMEEN_0=Allowed
KEY_ALGEMEEN_1=Back
KEY_ALGEMEEN_2=Cancel
KEY_ALGEMEEN_3=Continue
KEY_ALGEMEEN_4=On
KEY_ALGEMEEN_5=Off
KEY_CONFIGURATION_0=Music
KEY_CONFIGURATION_1=SoundEffects
KEY_CONFIGURATION_2=ColorBlind
KEY_CONFIGURATION_3=Tutorials
KEY_CONFIGURATION_4=Language
LANG1=English
LANG2=Dutch
*list:CAT_AAA
	Language
	Translator
*end
*list:CAT_ALGEMEEN_IGNORE
	ALLOWED
	BACK
	CANCEL
	Continue
	MOVES
	NEWGAME
	NO
	OKAY
	SCORE
	TERUG
	TIME
	UNDONE
	YES
	ON
	OFF
*end
*list:CAT_CONFIGURATION
	Music
	SoundEffects
	ColorBlind
	Tutorials
	Language
*end
*list:^CATEGORIES^
	AAA
	ALGEMEEN
	CONFIGURATION
*end
[SUPPORT]
LANGUAGES=English,Dutch
LANGUAGE_DEF=English
